{
 "title": "TRYTRY",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Device status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  req_time AS \"time\",\n  t_id,\n  device.d_status\nFROM transaction, device\nORDER BY device.d_id"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 0 },
   "content": "\n# Smart Cube Dashboard\n\n\n\n"
  },
  {
   "title": "Transactions over time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(req_time,$__interval),\n  avg(t_id) AS \"t_id\"\nFROM transaction\nWHERE\n  $__timeFilter(req_time)\nGROUP BY 1\nORDER BY $__timeGroup(req_time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(res_time,$__interval),\n  avg(t_id) AS \"t_id\"\nFROM transaction\nWHERE\n  $__timeFilter(res_time)\nGROUP BY 1\nORDER BY $__timeGroup(res_time,$__interval)"
    }
   ]
  },
  {
   "title": "Types of assignments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  req_time AS \"time\",\n  a_id\nFROM transaction\nWHERE\n  $__timeFilter(req_time)\nORDER BY req_time"
    }
   ]
  },
  {
   "title": "Count-threshold",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  req_time AS \"time\",\n  t_id\nFROM transaction\nWHERE\n  $__timeFilter(req_time)\nORDER BY req_time"
    }
   ]
  },
  {
   "title": "Transaction info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(req_time,$__interval),\n  avg(t_id) AS \"t_id\"\nFROM transaction\nWHERE\n  $__timeFilter(req_time)\nGROUP BY 1\nORDER BY $__timeGroup(req_time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(res_time,$__interval),\n  avg(t_id) AS \"t_id\"\nFROM transaction\nWHERE\n  $__timeFilter(res_time)\nGROUP BY 1\nORDER BY $__timeGroup(res_time,$__interval)"
    }
   ]
  },
  {
   "title": "User Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  req_time AS \"time\",\n  t_id,\n  User.u_type\nFROM transaction, User\nORDER BY t_id"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT s_id,s_name from service"
    }
   ]
  },
  {
   "title": "Device calls",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\nassigns.d_id,Count(assigns.d_id) as count \nFROM transaction, assigns\nWHERE\n  transaction.a_id = assigns.a_id\ngroup BY assigns.d_id "
    }
   ]
  },
  {
   "title": "Service calls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n Count(assigns.s_id) as count \nFROM transaction, assigns\nWHERE\n  transaction.a_id = assigns.a_id\ngroup BY assigns.s_id"
    }
   ]
  }
 ]
}